### ISSUE TITLE
Model output race condition when running multiple miners

### ISSUE THREAD

**Issue by Dekoze** [semperai/arbius#16]
Miners running Kandinsky-2 generate output image at ./cache/out-1.png which is later pinned to IPFS to generate cid. If a second running miner generates output for a different task between these steps a potentially wrong file and cid is generated for the first task.

Solutions:

1. Create unique output files such as {taskid}.png, I believe changing the filename results in a different cid? I don't know IPFS well but if so this change requires all miners to update naming consensus. This is probably more future-proof once multiple models are running etc. but does require cleaning up generated outputs occasionally.
2. Add a cache path field to MiningConfig.json that users can define on a per-miner basis. I've already done this locally as it doesn't break my IPFS cid generation so I'll create a pr

**Comment by Christophy** [comment]
For your reference:
https://docs.ipfs.tech/concepts/content-addressing/#what-is-a-cid
