### ISSUE TITLE
Add IPFS network check on boot of miner

### ISSUE THREAD

**Issue by kasumi-1** [semperai/arbius#2]

**Comment by slowsynapse** [comment]
Arbius has a $50 AIUS bounty for this issue!

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by yhl125** [comment]
I claim this bounty

**Comment by kasumi-1** [comment]
https://etherscan.io/tx/0x67ddaf0daac5ed698f6e781db6e705ebddbb83e974203dd031b392fa44376ed0

Thanks @yhl125 - this merged into miner-stage branch now :)
