### ISSUE TITLE
Improve min stake detection

### ISSUE THREAD

**Issue by kasumi-1** [semperai/arbius#7]
If tx reverts due to min stake, automatically restake immediately

**Comment by kasumi-1** [comment]
Arbius has a $250 AIUS bounty for this issue!

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by Solbacker175** [comment]
from web3 import Web3
from web3.exceptions import TransactionNotFound

# Initialize Web3 provider
web3 = Web3(Web3.HTTPProvider('https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID'))

# Address of the account submitting transactions
account_address = 'YOUR_ACCOUNT_ADDRESS'
private_key = 'YOUR_PRIVATE_KEY'

# Function to resubmit a transaction with increased stake
def resubmit_transaction(tx_hash, new_stake):
    try:
        # Get the failed transaction details
        tx = web3.eth.get_transaction(tx_hash)
        
        # Increase the stake amount
        tx['value'] = new_stake
        
        # Resign the transaction
        signed_tx = web3.eth.account.sign_transaction(tx, private_key)
        
        # Send the transaction
        tx_receipt = web3.eth.send_raw_transaction(signed_tx.rawTransaction)
        
        print(f"Transaction resubmitted: {tx_receipt.hex()}")
        
    except TransactionNotFound:
        print("Transaction not found.")

# Function to monitor for reverted transactions
def monitor_transactions():
    # Get all transactions sent by the account
    transactions = web3.eth.get_transaction_count(account_address)
    
    for nonce in range(transactions):
        try:
            # Get transaction details
            tx = web3.eth.get_transaction(account_address, nonce=nonce)
            
            # Check if the transaction reverted
            if tx['blockHash'] is None:
                # Resubmit transaction with increased stake
                new_stake = web3.eth.get_balance(account_address) // 10  # Increase stake by 10%
                resubmit_transaction(tx['hash'], new_stake)
                
        except TransactionNotFound:
            continue

# Main loop to continuously monitor transactions
while True:
    monitor_transactions()

**Comment by Christophy** [comment]
I claim this bounty
