### ISSUE TITLE
Support Stable Diffusion Video

### ISSUE THREAD

**Issue by kasumi-1** [semperai/arbius#9]
Implement and test a cog container built for svd and deploy it

**Comment by kasumi-1** [comment]
Arbius has a $500 AIUS bounty for this issue!

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by Christophy** [comment]
I claim this bounty

**Comment by Christophy** [comment]
Due to paused contract, cant deploy the model right now. will make PR after contract resume.

**Comment by kasumi-1** [comment]
@Christophy hey, we're unpaused

**Comment by Christophy** [comment]
@kasumi-1 
see https://github.com/semperai/arbius/pull/23
Ethereum address: 0xAB25FD559664f50554a740Dd28b729b6c8d6383f

**Comment by kasumi-1** [comment]
very cool, give me some time to review :)

**Comment by Christophy** [comment]
Just being curious, am I encouraged to set fees on the model?
I tried adding fee parameter on the model, but the model page seems not support it(I mean the "contracts" field in config.json file,  ).
![Uploading image.png…]()
